### ISSUE TITLE
The extension doesn't work

### ISSUE THREAD

**Issue by wenyongqd** [PaoloJN/youtube-ai-extension#1]
I installed extension as the instruction, it doesn't work. Could you help me figure out what I missed?
<img width="931" alt="Screenshot 2024-06-08 at 12 02 38 AM" src="https://github.com/PaoloJN/youtube-ai-extension/assets/46271263/ff2684f9-6493-4d33-afd8-c12c7958883a">

**Comment by PaoloJN** [comment]
Hey, just make sure it's enabled, then close and open your browser

hope that helps
Paolo Nessim

**Comment by wenyongqd** [comment]
It's enabled, and I have also removed and reinstalled but it still doesn't work.

https://github.com/PaoloJN/youtube-ai-extension/assets/46271263/a0d6de5d-7810-434f-a21f-063028e885f5

**Comment by PaoloJN** [comment]
did you restart your browser ?

**Comment by wenyongqd** [comment]
I did

**Comment by PaoloJN** [comment]
Still not working ? I should mention that it doesn't have a pop-up; it's just a content script

<img width="1509" alt="Screenshot 2024-06-07 at 2 28 10 AM" src="https://github.com/PaoloJN/youtube-ai-extension/assets/87121008/5d42d3a4-00dc-4cec-83c7-cff14b65c6a6">

**Comment by wenyongqd** [comment]
It still doesn't work, but I noticed the folder under build in my case is `chrome-mv3-prod` instead of `chrome-mv3-dev`

**Comment by wenyongqd** [comment]
It seems like my browser isser, it works in Incognito mode. Let's my try clear my data.

**Comment by wenyongqd** [comment]
@PaoloJN 
I may have identified the issue, the extension only works when my account was signed out, is it possible to fix it?
<img width="567" alt="Screenshot 2024-06-08 at 11 05 53 AM" src="https://github.com/PaoloJN/youtube-ai-extension/assets/46271263/1c637a01-2840-43a7-9da2-3e3bf1133d01">

**Comment by PaoloJN** [comment]
I believe the issue is because of YouTube's new layout (https://www.youtube.com/new). I still have the old layout, which is works with the extension because of the uBlock Origin extension that reverts to the old layout.

Here is a tutorial on how to switch back to the old layout: https://www.youtube.com/watch?v=J0L_nYtNlqs. Once you switch back, the extension should work fine.
